---
name: Deploy
run-name: Deploy to ${{ inputs.environment }}

on: 
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
        description: "Environment to deploy to"
      project-name:
        type: string
        required: true
        description: "Name of the project to deploy"
      version:
        type: string
        required: true
        description: "version deploying"
      is-dry-run:
        type: boolean
        default: true

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    concurrency: ${{ inputs.environment }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2

      - name: Test artifact
        run: |
          unzip ${{ inputs.project-name }}.zip
          ls -atlh

      - name: Login to Azure
        if: ${{ ! inputs.is-dry-run }}
        uses: Azure/login@1f63701bf3e6892515f1b7ce2d2bf1708b46beaf # v1.4.3
        with:
          creds: ${{ secrets.KEY_VAULT_SP }}  # From the environment.secrets

      - name: Configure App
        if: ${{ ! inputs.is-dry-run }}
        run: |
          az webapp config appsettings set -g ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} \
            -n ${{ secrets.AZURE_APP_NAME }} --slot staging \
            --settings DD_VERSION=${{ inputs.version }}

      - name: Deploy App
        if: ${{ ! inputs.is-dry-run }}
        run: |
          az webapp deployment source config-zip \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP_NAME }} \
            --name ${{ secrets.AZURE_APP_NAME }} --slot staging --src ./publish.zip
