---
name: CD

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write
  id-token: write
  checks: write

jobs:
  version:
    uses: ./.github/workflows/_version.yml


  test:
    uses: ./.github/workflows/_test.yml


  build:
    needs:
      - test
      - version
    strategy:
      matrix:
        project-name:
          - AdminConsole
          - Api
    uses: ./.github/workflows/_build.yml
    with:
      project-name: ${{ matrix.project-name }}
      project-path: ./src/${{ matrix.project-name }}
      version: ${{ needs.version.outputs.version }}


  deploy-devtest:
    strategy:
      matrix:
        project-name:
          - AdminConsole
          - Api
    needs:
      - build
      - version
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    with:
      environment: devtest
      project-name: ${{ matrix.project-name }}
      version: ${{ needs.version.outputs.version }}
