---
name: CD - Production

on:
  workflow_dispatch: 
    inputs: {}

permissions:
  contents: write
  deployments: write
  id-token: write
  checks: write

jobs:
  test:
    uses: ./.github/workflows/_test.yml

  build:
    needs:
      - test
    uses: ./.github/workflows/_build.yml
    with:
      is-release: true

  production-deploy:
    needs:
      - build
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    with:
      environment: production
      version: ${{ needs.build.outputs.version }}  # Solely used to see version hit web server
