---
name: CD - Staging

on:
  workflow_dispatch: 
    inputs: {}
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/_test.yml

  build:
    needs:
      - test
    uses: ./.github/workflows/_build.yml
    with:
      project-name: AdminConsole
      project-path: ./src/AdminConsole

  staging-deploy:
    needs:
      - build
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    with:
      environment: staging
      project-name: AdminConsole
      version: ${{ needs.build.outputs.version }}  # Solely used to see version hit web server
