---
name: CD - Staging

on:
  workflow_dispatch: 
    inputs: {}
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  checks: write

jobs:
  test:
    uses: ./.github/workflows/_test.yml


  build:
    needs:
      - test
    strategy:
      matrix:
        project-name: 
          - AdminConsole
          - Api
    uses: ./.github/workflows/_build.yml
    with:
      project-name: ${{ matrix.project-name }}
      project-path: ./src/${{ matrix.project-name }}


  staging-deploy:
    strategy:
      matrix:
        project-name: 
          - AdminConsole
          - Api
    needs:
      - build
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    with:
      environment: staging
      project-name: ${{ matrix.project-name }}
