---
name: Release & Deploy

on:
  workflow_dispatch:
    inputs:
      deploy-api:
        description: "Deploy Api"
        type: boolean
        default: false
      deploy-adminconsole:
        description: "Deploy AdminConsole"
        type: boolean
        default: false


permissions:
  contents: write
  deployments: write
  id-token: write
  checks: write
  packages: write

jobs:
  version:
    uses: ./.github/workflows/_version.yml
    with:
      is-release: true


  test:
    uses: ./.github/workflows/_test.yml


  build:
    needs:
      - test
      - version
    strategy:
      matrix:
        project-name:
          - AdminConsole
          - Api
    uses: ./.github/workflows/_build.yml
    with:
      project-name: ${{ matrix.project-name }}
      project-path: ./src/${{ matrix.project-name }}
      version: ${{ needs.version.outputs.version }}


  release:
    needs:
      - build
      - version
    uses: ./.github/workflows/_release.yml
    with:
      version: ${{ needs.version.outputs.version }}
      is-dry-run: false


  # deploy-qa-api:
  #   if: ${{ inputs.deploy-api }}
  #   needs:
  #     - build
  #   uses: ./.github/workflows/_deploy.yml
  #   secrets: inherit
  #   with:
  #     environment: qa
  #     project-name: AdminConsole
  #     version: ${{ needs.version.outputs.version }}


  # deploy-qa-adminconsole:
  #   if: ${{ inputs.deploy-adminconsole }}
  #   needs:
  #     - build
  #   uses: ./.github/workflows/_deploy.yml
  #   secrets: inherit
  #   with:
  #     environment: qa
  #     project-name: AdminConsole
  #     version: ${{ needs.version.outputs.version }}


  deploy-prod-api:
    if: ${{ inputs.deploy-api }}
    needs:
      - build
      - version
      - release
      # - deploy-qa-api
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    with:
      environment: production
      project-name: Api
      version: ${{ needs.version.outputs.version }}


  deploy-prod-adminconsole:
    if: ${{ inputs.deploy-adminconsole }}
    needs:
      - build
      - version
      - release
      # - deploy-qa-admin-console
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    with:
      environment: production
      project-name: AdminConsole
      version: ${{ needs.version.outputs.version }}
