name: docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  # Build the image without deploying just to make sure the dockerfile is valid
  build:
    strategy:
      matrix:
        app:
          - Api
          # - AdminConsole
          - Self-Host
        include:
          - app: Api
            dockerfile: Api.dockerfile
          - app: AdminConsole
            dockerfile: AdminConsole.dockerfile
          - app: Self-Host
            dockerfile: self-host/Dockerfile

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # 3.0.0

      - name: Build & push image
        run: >
          docker buildx build
          --file ${{ matrix.dockerfile }}
          --platform linux/amd64,linux/arm64
          --output type=tar,dest=image.tar
          .

  # Build and deploy the image
  deploy:
    if: ${{ github.event_name != 'pull_request' }}

    strategy:
      matrix:
        app:
          - Api
          # - AdminConsole
          - Self-Host
        include:
          - app: Api
            dockerfile: Api.dockerfile
            repository: passwordless-test-api
          - app: AdminConsole
            dockerfile: AdminConsole.dockerfile
            repository: passwordless-test-admin-console
          - app: Self-Host
            dockerfile: self-host/Dockerfile
            repository: passwordless-self-host

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # 3.0.0

      - name: Login to GitHub Container Registry
        run: >
          echo ${{ secrets.GITHUB_TOKEN }} |
          docker login ghcr.io --username ${{ github.actor }} --password-stdin

      - name: Build & push image
        run: >
          docker buildx build
          --file ${{ matrix.dockerfile }}
          --platform linux/amd64,linux/arm64
          --push
          --tag ghcr.io/passwordless/${{ matrix.repository }}:latest
          ${{ github.event_name == 'release' && '--tag ghcr.io/passwordless/${{ matrix.repository }}:$GITHUB_REF_NAME' || '' }}
          ${{ github.event_name == 'release' && '--tag ghcr.io/passwordless/${{ matrix.repository }}:stable' || '' }}
          .